require( "./lib-sniff-arguments-spacing.js" );
require( "./lib-sniff-array-literal.js" );
require( "./lib-sniff-comma-punctuator-spacing.js" );
require( "./lib-sniff-compound-statement.js" );
require( "./lib-sniff-empty-constructs-spacing.js" );
require( "./lib-sniff-function-naming-conventions.js" );
require( "./lib-sniff-indentation.js" );
require( "./lib-sniff-line-length.js" );
require( "./lib-sniff-line-spacing.js" );
require( "./lib-sniff-object-literal-spacing.js" );
require( "./lib-sniff-operator-spacing.js" );
require( "./lib-sniff-parameters-spacing.js" );
require( "./lib-sniff-quote-conventions.js" );
require( "./lib-sniff-semicolon-punctuator-spacing.js" );
require( "./lib-sniff-ternary-conditional-spacing.js" );
require( "./lib-sniff-unary-expression.js" );
require( "./lib-sniff-var-dec-per-scope.js" );
//require( "./lib-sniff-variable-naming-conventions.js" );
require( "./lib-sniff-chained-methods.js" );
require( "./lib-sniff-object-declaration-conventions.js" );
require( "./lib-sniff-array-declaration-conventions.js" );
require( "./lib-sniff-array-declaration-conventions.js" );
require( "./lib-sniff-new-naming-conventions.js" );


require( "./lib-reporter" );
require( "./lib-cli" );
require( "./lib-utils" );
require( "./lib-dictionary" );
require( "./lib-logger" );
require( "./lib-mediator" );
require( "./lib-source-code" );
require( "./lib-syntax-analizer" );
require( "./lib-sniffer" );

require( "./lib-formatter-xml" );
require( "./lib-formatter-summary" );
require( "./lib-formatter-full" );
require( "./lib-formatter-checkstyle" );
