#!/usr/bin/env node
var esprima = require("esprima"),
    sniffer = require('./lib/Sniffer'),
    Standard = require('./standard/Idiomatic'),
    fs = require('fs'),
    path,
    options = {},
    helpScreen = "Usage: jscs <path>\n" +
                    "<path> - filename or dir to sniff\n" +
                    "[--standard=<Standard>] - apply specified standard\n" +
                    "[--trace] - show tokens\n",

    processFile = function( path, fn ) {
            var data = fs.readFileSync( path, 'utf-8' );
                    console.log( "File: " + path );
                    fn( data );
    },
    processDir = function( path, fn ) {
            var dir = fs.readdirSync( path );
            dir && dir.forEach(function( file ){
                    var re = /\.js$/gi;
                    if ( re.test( file ) ) {
                            processFile( path + "/" + file, fn );
                    }
            });
    },
    processPath = function( path, fn ) {
            var stat;
            if (  !fs.existsSync( path ) ) {
                    return console.error( helpScreen );
            }
            stat = fs.statSync( path );
            return stat.isFile() ? processFile( path, fn ) : processDir( path, fn );
    };

if ( process.argv.length < 3 ) {
    return console.log( helpScreen );
}
// Obtain CLI arguments
process.argv.slice( 2 ).forEach(function( arg ){
    var slices;
    if ( arg === "--help" ) {
            return console.log( helpScreen );
    }
    if ( arg.indexOf( "--" ) === 0 ) {
            slices = arg.split( "=" );
            options[ slices[0] ] = slices[ 1 ] || null;
    } else {
            path = arg;
    }
});

processPath( path , function( data ) {
    if ( typeof options["--trace"] !== "undefined" ) {
        console.log( sniffer.trace(data, Standard) );
    } else {
        sniffer.run( data, Standard ).report();
    }
});
