#!/usr/bin/env node
// npm install esprima -g
var esprima = require("esprima"),
    sniffer = require('./lib/Sniffer'),
    Standard = require('./standard/Idiomatic'),
    fs = require('fs'),
    srcCodeFile;

if ( process.argv.length < 3 ) {
    throw new Error( "Correct syntax: ./t filename.js" );
}
srcCodeFile = process.argv.slice(2)[0];

/**
 * @TODO: read all files recursively in given folder
 * @TODO: proper error messaging when invalid arguments or cannot find the file
 */
fs.readFile(srcCodeFile, "UTF-8", function (err, data) {
    if (err) {
        throw err;
    }
    sniffer.run( data, Standard ).report();
});
